apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ebensch-portfolio"
  namespace: ebensch-portfolio
  labels:
    app: "ebensch-portfolio"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ebensch-portfolio"
  template:
    metadata:
      labels:
        app: "ebensch-portfolio"
    spec:
      containers:
        - image: "ghcr.io/ebensch/portfolio-oc:d1cd68063e4b6b6aa7d20d0ec1d324242c8b6657"
          name: "ebensch-portfolio"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
